### PR TITLE
Refactoring of controller

### PR DESCRIPTION
**Pull request by kakposoe**
Small refactor of code.

### CODE REVIEW

**Comment by julienbourdeau** [comment]
I like the use of the second parameter of input (or get). I forgot about that!

Other than that, I don't see what's better.
I even think if you're passing `?sort=yolo`, it's going to break 🤔 There are no test on that part.

**Comment by kakposoe** [comment]
@julienbourdeau Fair point on the random `?sort=` parameter being passed. I overlooked this.

To be fair, I would agree that not much is better, more so of a strip of what can be inlined (apart from the `sort` point you brought up).

Should I explore a test to make sure this isn't an issue?

**Comment by julienbourdeau** [comment]
I added a tests yesterday night for this controller.

To be honest, I think it's fine the way it is. I like having  `$request->get()` at the top, so I know that parameters can be passed.

I updated to use the default value (second parameters) tho! Thanks a lot for that 🙏

**Comment by kakposoe** [comment]
@julienbourdeau Welcome.

**Pull request closed without merging**
