### PR TITLE
Support many databases (fixes #4)

### LINKED ISSUE #4: Support multiple databases
Hi, great package idea!

I noticed the package appears to only support mysql.
The code is in `LogRouteUsage.php`
```php
DB::statement(
    "INSERT INTO route_usage
            (`identifier`, `method`, `path`, `status_code`, `action`, `created_at`, `updated_at`)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        ON DUPLICATE KEY UPDATE `updated_at` = '{$date}'",
    [$identifier, $method, $path, $status_code, $action, $date, $date]
);
```

I think it would be possible to support multiple databases with a change in LogRouteUsage.php

I'll submit a pull request once I've got the tests passing 👍

### PR DESCRIPTION
**Pull request by ingalless**
Hi!

I had to make a modification to one test as other databases won't necessarily insert a timestamp with microseconds. If that's not acceptable I understand.

If you want to test, my phpunit.xml was configured as:
```xml
<env name="DB_CONNECTION" value="sqlite"/>
<env name="DB_DATABASE" value=":memory:"/>
```

Fixes #4 
Might also bring support for Redis?

### CODE REVIEW

**Comment by ingalless** [comment]
@julienbourdeau I'm happy to reopen this pull request off the latest commit if you'd like the merge commits removed?

**Comment by julienbourdeau** [comment]
I looked into a little bit. Overall, I would definitely want to add support for other databases.

I'm not sure about using Eloquent here. `updateOrCreate` will create 2 db requests, instead of one.
But maybe 2 queries is best because locks don't behave the same way ¯\_(ツ)_/¯ 

I'm not so sure what solution gets the best performance here. I'm actually not sure there is a difference. 

With Eloquent, on first call:
Screenshot 2019-10-27 at 19 40 28

With Eloquent, on other calls
Screenshot 2019-10-27 at 19 40 40

With raw query (everytime)
Screenshot 2019-10-27 at 19 41 10

**Comment by ingalless** [comment]
My reasoning with using Eloquent was that we utilise the underlying power of Laravel's SQL grammar. 

If performance is an issue, why not add a migration to add an index on the identifier column if there isn't already?

**Comment by kasperhartwich** [comment]
@julienbourdeau If you look into supporting sqlsrv with raw sql, you will have to do two queries, as ON DUPLICATE KEY is not supported.
I think this PR sounds like the right solution.

**Comment by oaloria** [comment]
Is this PR getting merged soon? Waiting for it!

**Comment by ingalless** [comment]
@julienbourdeau Any further thoughts on this issue?

**Comment by julienbourdeau** [comment]
Let's try this, we'll see if it needs to be optimized later

**Pull request merged**
